// Generated by CoffeeScript 1.7.1
var ArgumentParser, args, create, parser;

ArgumentParser = (require('argparse')).ArgumentParser;

create = require('./svg-font-create');

parser = new ArgumentParser({
  version: (require('./package.json')).version,
  addHelp: true,
  description: 'Create SVG font from separate images'
});

parser.addArgument(['-n', '--name'], {
  help: 'Font name'
});

parser.addArgument(['-i', '--input_dir'], {
  help: 'Source images path (eg. "./src")',
  required: true
});

parser.addArgument(['-o', '--output_dir'], {
  help: 'Output font file path (eg. "./dist")',
  required: true
});

parser.addArgument(['-p', '--prefix'], {
  help: 'Prefix for CSS classes'
});

args = parser.parseArgs();

if (args) {
  create(args);
}
